services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: votingdb
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: voting123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votingdb
      SPRING_DATASOURCE_USERNAME: voting
      SPRING_DATASOURCE_PASSWORD: voting123

volumes:
  pgdata:
