spring.application.name=voting
spring.datasource.url=jdbc:postgresql://localhost:5432/votingdb
spring.datasource.username=voting
spring.datasource.password=voting123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
